"""empty message

Revision ID: 61c7b535ebb6
Revises: 825ed20cd47e
Create Date: 2019-12-26 21:14:27.933210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61c7b535ebb6'
down_revision = '825ed20cd47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gname', sa.String(length=80), nullable=True),
    sa.Column('gtype', sa.String(length=2), nullable=True),
    sa.Column('gprice', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gname')
    )
    op.drop_index('gname', table_name='goods')
    op.drop_table('goods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('gtype', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('gprice', mysql.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('gname', 'goods', ['gname'], unique=True)
    op.drop_table('t_goods')
    # ### end Alembic commands ###
