"""empty message

Revision ID: b5461301277d
Revises: 61c7b535ebb6
Create Date: 2019-12-26 21:18:49.546173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5461301277d'
down_revision = '61c7b535ebb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('price', sa.String(length=5), nullable=True))
    op.drop_column('t_goods', 'gprice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('gprice', mysql.VARCHAR(length=5), nullable=True))
    op.drop_column('t_goods', 'price')
    # ### end Alembic commands ###
